version: "3"
services:
  builder:
    build: ./builder
    volumes:
      - .:/work
    working_dir: /work
  superbuilder:
    build:
      context: ./builder
      args:
        build_as_root: "yes"
    volumes:
      - .:/work
    working_dir: /work
  tester:
    image: rockylinux:9
    volumes:
      - .:/work
    working_dir: /work
