version: "3"
services:
  builder:
    build:
      context: ./builder
      args:
        base_image: ${base_image}
    volumes:
      - .:/work
    working_dir: /work
  superbuilder:
    build:
      context: ./builder
      args:
        build_as_root: "yes"
        base_image: ${base_image}
    volumes:
      - .:/work
    working_dir: /work
  tester:
    image: ${base_image}
    volumes:
      - .:/work
    working_dir: /work
