name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  checkinstaller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl -sLRO https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    - run: sha256sum awscli-exe-linux-x86_64.zip > example.sha256
    - run: unzip awscli-exe-linux-x86_64.zip
    - run: aws/dist/aws --version > example.version
    - run: head example.*
    - run: ls -alF
