name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  checkinstaller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        INSTALLER_ZIP: awscli-exe-linux-x86_64.zip
      run: |
        set -x
        #
        : download installer
        curl -sLRO https://awscli.amazonaws.com/"$INSTALLER_ZIP"
        #
        : skip rest if installer has not changed
        if sha256sum -c "$INSTALLER_ZIP".sha256 ; then exit 0 ; fi
        #
        : update checksum
        sha256sum "$INSTALLER_ZIP" > "$INSTALLER_ZIP".sha256
        #
        : extract version
        unzip -q "$INSTALLER_ZIP"
        aws/dist/aws --version | tee "$INSTALLER_ZIP".version
        version=$(gawk -v RS=' |\n' -v FS=/ '$1 == "aws-cli" {print $2}' "$INSTALLER_ZIP".version)
        printf 'version: %q\n' "$version"
        #
        : push updated installer details to repo
        git config user.name "$GITHUB_ACTOR"
        git config user.email "${GITHUB_REPOSITORY//\//+}+${GITHUB_WORKFLOW}@github.io"
        git add "$INSTALLER_ZIP".*
        git commit -m "version $version is now available"
        git push
