name: check for new installer
on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
  # schedule:
  #   - cron: "15 18 * * *"
jobs:
  check_for_new_installer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check for new installer
      run: |
        git rm -q -f --ignore-unmatch -- *.version
        bash -x check_for_new_installer | xargs --no-run-if-empty git add
    - name: rebuild spec file, etc.
      run: ./respecit | xargs --no-run-if-empty git add
    - name: check for changes to commit
      id: check
      continue-on-error: true
      run: git diff --cached --name-status --exit-code
    - name: push updated installer details
      if: steps.check.outcome == 'failure'
      shell: bash
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "${GITHUB_REPOSITORY//\//+}+${GITHUB_WORKFLOW// /-}@github.io"
        git commit --file aws-cli.version
        git push
