name: check for new installer
on:
  schedule:
    - cron: "50 21 * * 6"
jobs:
  check_for_new_installer:
    runs-on: ubuntu-latest
    env:
      INSTALLER_ZIP: awscli-exe-linux-x86_64.zip
    steps:
    - uses: actions/checkout@v2
    - name: download installer
      run: curl -sLRO https://awscli.amazonaws.com/"$INSTALLER_ZIP"
    - shell: bash
      run: |
        set -x
        #
        : skip rest if installer has not changed
        if sha256sum -c "$INSTALLER_ZIP".sha256 ; then exit 0 ; fi
        #
        : update checksum
        sha256sum "$INSTALLER_ZIP" > "$INSTALLER_ZIP".sha256
        #
        : extract version
        unzip -q "$INSTALLER_ZIP"
        git rm -q -f --ignore-unmatch -- *.version
        versions=$(aws/dist/aws --version)
        printf '= %q\n' $versions
        for pv in $versions
        do
          product=$(echo "${pv%%/*}" | tr '[:upper:]' '[:lower:]')
          version=${pv#*/}
          case "$product" in
            aws-cli|python)  keep=yes ;;
            *)               keep=no  ;;
          esac
          if [ $keep = yes ]
          then
            printf '%s\n' "$version" > "$product".version
            git add "$product".version
          fi
        done
        #
        : push updated installer details to repo
        git config user.name "$GITHUB_ACTOR"
        git config user.email "${GITHUB_REPOSITORY//\//+}+${GITHUB_WORKFLOW// /-}@github.io"
        git add *.sha256 *.version
        git commit --file aws-cli.version
        git push
